"""Stage 4 — verify.

Per AC.OREK.3 — input :class:`RawACs` → output :class:`ContractDraft`
written to ``<workspace>/.loam/extractions/<repo-id>/contract-draft.md``
and ``contract-draft.yaml``.

Per Surface #10 + F2 RF gap #3 (plan-doc §10) — Cycle 2 fills the
markdown with band-tagged ACs. Cycle 1 ships only the skeleton
markdown with named anchor comments where Cycle 2 will inject:

- ``<!-- ACS_TABLE_HERE -->`` — Cycle 2 ratification table.
- ``<!-- COVERAGE_GAPS_HERE -->`` — unhandled paths section.

The "ODD §2.5 coverage check" promised in AC.OREK.3 is a structural
check at this stage: every input path either appears in an AC's
``backing_files`` (Cycle 2+) OR in the unhandled-paths section. With
zero ACs in Cycle 1, the check is shape-only — every input path is
unhandled. Cycle 2's bands and Cycle 3+4's adapters make the check
meaningful.
"""

from __future__ import annotations

import datetime as _dt

import yaml

from .errors import StageError
from .observability import write_audit_entry
from .spec import ContractDraft, ExtractionConfig, RawACs
from .state import extraction_dir, load_state, save_state


def _now_iso() -> str:
    return _dt.datetime.now(_dt.timezone.utc).isoformat()


def _render_contract_markdown(
    *,
    config: ExtractionConfig,
    raw: RawACs,
) -> str:
    """Render the contract draft markdown.

    Cycle 1 shape: title + status banner + AC table anchor + unhandled
    paths section + provenance footer. Cycle 2 fills the AC table.
    """
    lines: list[str] = []
    lines.append(f"# Contract draft — {config.repo_path.name}")
    lines.append("")
    lines.append(
        "**Status:** DRAFT — auto-generated by `loam odd-extract` "
        f"v0.1.8 Cycle 1 scaffold."
    )
    lines.append("")
    lines.append(f"**Repo path:** `{config.repo_path}`")
    lines.append(f"**Repo ID:** `{config.repo_id}`")
    lines.append(f"**Generated at:** {raw.created_at}")
    lines.append(f"**Dry run:** {config.dry_run}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Acceptance criteria")
    lines.append("")
    lines.append("<!-- ACS_TABLE_HERE -->")
    lines.append("")
    if raw.acs:
        # Band-tagged rendering per v0.1.8 Cycle 2 (AC.BANDS.1+3) —
        # if every AC dict carries a ``confidence`` key, render the
        # banded summary table + per-AC sections; otherwise fall back
        # to the Cycle 1 generic key-value rendering.
        all_banded = all(
            isinstance(ac, dict) and "confidence" in ac
            for ac in raw.acs
        )
        if all_banded:
            lines.append("| AC | Band | Evidence kind | Citations |")
            lines.append("|----|------|---------------|-----------|")
            for ac in raw.acs:
                ac_id = ac.get("ac_id", "(unnamed)")
                band = ac.get("confidence", "?")
                ev = ac.get("evidence", {}) or {}
                kind = ev.get("kind", "?")
                cites = ev.get("citations") or []
                cites_summary = (
                    f"{len(cites)} citation(s)" if cites else "(none)"
                )
                lines.append(
                    f"| {ac_id} | {band} | {kind} | {cites_summary} |"
                )
            lines.append("")
            for ac in raw.acs:
                ac_id = ac.get("ac_id", "(unnamed)")
                band = ac.get("confidence", "?")
                lines.append(f"### {ac_id} — {band}")
                lines.append("")
                lines.append(f"**Text:** {ac.get('text', '')}")
                lines.append("")
                ev = ac.get("evidence", {}) or {}
                lines.append(f"- **Evidence kind:** {ev.get('kind', '?')}")
                cites = ev.get("citations") or []
                if cites:
                    lines.append(f"- **Citations:** {len(cites)} entries")
                    for c in cites:
                        lines.append(f"  - `{c}`")
                if ev.get("repo_sha"):
                    lines.append(f"- **Repo SHA:** `{ev['repo_sha']}`")
                if ev.get("rationale"):
                    lines.append(f"- **Rationale:** {ev['rationale']}")
                if ac.get("backing_files"):
                    lines.append(
                        f"- **Backing files:** "
                        f"{len(ac['backing_files'])} file(s)"
                    )
                lines.append("")
        else:
            lines.append("(Cycle 1 raw shape — bands not yet attached.)")
            lines.append("")
            for idx, ac in enumerate(raw.acs, 1):
                lines.append(f"### AC.{idx}")
                lines.append("")
                for k, v in ac.items():
                    lines.append(f"- **{k}:** {v}")
                lines.append("")
    else:
        lines.append(
            "_No ACs extracted in this run. Cycle 1's scaffold "
            "ships zero language adapters; Cycles 3 (Ruby/Rails) "
            "and 4 (Python) populate this section._"
        )
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Unhandled paths")
    lines.append("")
    lines.append("<!-- COVERAGE_GAPS_HERE -->")
    lines.append("")
    if raw.unhandled_paths:
        lines.append(
            f"_{len(raw.unhandled_paths)} path(s) had no language "
            "adapter coverage:_"
        )
        lines.append("")
        for p in raw.unhandled_paths:
            lines.append(f"- `{p}`")
        lines.append("")
    else:
        lines.append("_No unhandled paths._")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Provenance")
    lines.append("")
    lines.append(
        "- Plan-doc: "
        "`docs/rebuild/plans/v0-1-8-cycle-1-odd-extractor-scaffolding.md`"
    )
    lines.append(
        "- Master plan: `docs/rebuild/plans/v0-1-8-master-plan.md`"
    )
    lines.append(
        "- Per-stage artefacts: `<workspace>/.loam/extractions/"
        f"{config.repo_id}/`"
    )
    lines.append("")
    return "\n".join(lines)


def verify_contract(
    *,
    config: ExtractionConfig,
    raw: RawACs,
    timestamp: str | None = None,
) -> ContractDraft:
    """Run Stage 4 — verify.

    Returns :class:`ContractDraft`; writes ``contract-draft.md`` and
    ``contract-draft.yaml`` artefacts; appends ``stage_complete``
    audit-log entry + ``extraction_end`` bookend; updates
    ``state.yaml``.

    Per the structural ODD §2.5 check: every path in the input must
    appear either in an AC's ``backing_files`` (Cycle 2+) or in
    ``unhandled_paths``. Cycle 1's check verifies this contract is
    structurally satisfiable; raises :class:`StageError` on
    accidentally-dropped paths.

    ``timestamp`` is injectable for deterministic tests.
    """
    ext_dir = extraction_dir(config.workspace_root, config.repo_id)
    ts = timestamp if timestamp is not None else _now_iso()

    # Structural ODD §2.5 self-check (shape-only in Cycle 1):
    # every path that came into Stage 3 must appear either as
    # backing_files of some AC OR in unhandled_paths. Without
    # bands, ``backing_files`` is unmodelled — we only verify the
    # unhandled side. Cycle 2 extends this check.
    backed_paths: set[str] = set()
    for ac in raw.acs:
        for p in ac.get("backing_files", []) or []:
            backed_paths.add(str(p))
    if not isinstance(raw.unhandled_paths, list):
        raise StageError(
            "verify: raw-acs.unhandled_paths is not a list — "
            "extraction state is malformed"
        )

    markdown = _render_contract_markdown(config=config, raw=raw)
    md_path = ext_dir / "contract-draft.md"
    md_path.write_text(markdown, encoding="utf-8")

    # Per AC.OE.CONTRACT-FULL.{1,2} (v0.2.1 corrective F1) — the
    # contract-draft.yaml sidecar carries the full ``acs:`` list +
    # ``unhandled_paths:`` list so downstream consumers (notably
    # ``loam_pr_safety.contract.read_contract``) can construct a
    # populated :class:`BandedContract` without a separate read of
    # ``raw-acs.yaml``. Producer-side single-source-of-truth.
    #
    # Shape: ``acs`` carries the same ``list[dict]`` ``RawACs.acs``
    # holds (each dict is the ``BandedAC.model_dump()`` round-trip
    # shape). ``unhandled_paths`` is string-coerced because YAML
    # ``safe_dump`` cannot serialize ``Path`` objects directly.
    sidecar_payload = {
        "schema_version": 1,
        "extraction_id": config.repo_id,
        "repo_path": str(config.repo_path),
        "ac_count": len(raw.acs),
        "unhandled_count": len(raw.unhandled_paths),
        "dry_run": config.dry_run,
        "created_at": ts,
        "acs": list(raw.acs),
        "unhandled_paths": [str(p) for p in raw.unhandled_paths],
    }
    yaml_path = ext_dir / "contract-draft.yaml"
    yaml_path.write_text(
        yaml.safe_dump(sidecar_payload, sort_keys=False),
        encoding="utf-8",
    )

    draft = ContractDraft(
        extraction_id=config.repo_id,
        markdown_path=md_path,
        sidecar_path=yaml_path,
        ac_count=len(raw.acs),
        unhandled_count=len(raw.unhandled_paths),
        created_at=ts,
    )

    state = load_state(ext_dir)
    if state is None:
        from .state import ExtractionState

        state = ExtractionState(
            extraction_id=config.repo_id,
            repo_path=str(config.repo_path),
            workspace_root=str(config.workspace_root),
            init_complete=True,
            analyze_complete=True,
            generate_complete=True,
        )
    state.verify_complete = True
    state.last_updated_at = ts
    state.artefacts["contract_md"] = md_path.relative_to(ext_dir).as_posix()
    state.artefacts["contract_yaml"] = yaml_path.relative_to(ext_dir).as_posix()
    save_state(ext_dir, state)

    write_audit_entry(
        ext_dir,
        event_kind="stage_complete",
        extraction_id=config.repo_id,
        stage="verify",
        artefact_path=md_path.relative_to(ext_dir).as_posix(),
        notes=(
            f"ac_count={len(raw.acs)} "
            f"unhandled_count={len(raw.unhandled_paths)}"
        ),
        timestamp=ts,
    )
    write_audit_entry(
        ext_dir,
        event_kind="extraction_end",
        extraction_id=config.repo_id,
        notes=f"dry_run={config.dry_run}",
        timestamp=ts,
    )

    return draft
