# Copyright 2026 Luke Ivers and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""AC.WVS-FRESH.2 — the surface is persona-owned, not user-operated: the
refresh is driven by the events that change work-state (the persona's
own lifecycle), not by a command the user must run.

Verifies the refresh entry-point is invoked by a lifecycle-event path
(the hook, fed a Claude-Code event envelope), with no user-issued
command in the trigger path. The carrier is FORK F-1 (d): a hook that
regenerates the openable file (a) AND emits the in-context block (c)
off the SHARED aggregator.

Plan: docs/plans/work-visibility-surface.md §5.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from loam.primary_persona.work_visibility_presenters import (
    IN_CONTEXT_MARKER,
    in_context_block,
    status_file_path,
)

import loam.primary_persona.hooks_work_visibility as hook_mod

from _helpers_d40 import FakeTrackerClient, make_projection


def test_AC_WVS_FRESH_2_hook_event_drives_refresh(tmp_path: Path) -> None:
    """A Claude-Code lifecycle-event envelope (no user command) drives
    the hook, which regenerates the openable file AND returns the
    in-context block — the refresh trigger is a lifecycle event."""
    envelope = {"workspace": {"project_dir": str(tmp_path)}}
    output = hook_mod.run(envelope)

    # (a) the openable artifact was regenerated by the lifecycle event.
    assert status_file_path(tmp_path).exists()
    # (c) the in-context block is emitted as additionalContext.
    block = output["hookSpecificOutput"]["additionalContext"]
    assert IN_CONTEXT_MARKER in block
    assert "right now" in block.lower()


def test_AC_WVS_FRESH_2_in_context_block_carries_live_surface(
    tmp_path: Path,
) -> None:
    """The in-context presenter renders the live surface so the persona
    HOLDS current work-state (proactive, no user pull)."""
    block = in_context_block(
        tmp_path,
        tracker_factory=lambda: FakeTrackerClient(
            query_result=(make_projection("a", status="active"),)
        ),
    )
    assert IN_CONTEXT_MARKER in block
    assert "working on 1" in block.lower()


def test_AC_WVS_FRESH_2_hook_fail_closed_on_bad_envelope() -> None:
    """A malformed envelope (no workspace, no cwd) → empty
    additionalContext, never raises (fail-closed; the host event is
    never broken)."""
    output = hook_mod.run({"garbage": True})
    assert output["hookSpecificOutput"]["additionalContext"] == ""


def test_AC_WVS_FRESH_2_hook_cli_exits_zero(tmp_path: Path) -> None:
    """The hook CLI reads a stdin envelope and exits 0 (the fail-closed
    contract — a hook never crashes the host)."""
    # src/loam/primary_persona/hooks_work_visibility.py -> component root.
    component_root = Path(hook_mod.__file__).resolve().parents[3]
    hook_path = component_root / "hooks" / "work_visibility_hook.py"
    assert hook_path.exists(), f"hook script not found at {hook_path}"
    envelope = json.dumps({"cwd": str(tmp_path)})
    proc = subprocess.run(
        [sys.executable, str(hook_path)],
        input=envelope,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0
    payload = json.loads(proc.stdout)
    assert "hookSpecificOutput" in payload
